ARG JUPYTERHUB_HUB_HELM_VERSION=4.3.2
FROM quay.io/jupyterhub/k8s-hub:$JUPYTERHUB_HUB_HELM_VERSION AS release

# By default, the notebook base image is set to non-sudo user joyvan. This makes root-ful actions difficult.
USER root

ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && \
    apt install --no-install-recommends -y \
    tzdata
RUN ln -fs /usr/share/zoneinfo/America/Alaska /etc/localtime
RUN dpkg-reconfigure --frontend noninteractive tzdata
RUN apt install --no-install-recommends -y \
    python3 \
    python3-pip \
    less \
    vim \
    patch

RUN python3 --version
RUN python3 -m pip install --upgrade \
    awscli \
    pyyaml \
    boto3 \
    kubernetes \
    kubernetes_asyncio \
    opensarlab-backend==1.0.4 \
    --

# Not sure what this does and may not be needed
#RUN cp -r /tmp/site-packages/* /usr/local/lib/python*/site-packages

USER jovyan 
