---
# yamllint disable rule:line-length
# https://docs.github.com/en/actions/publishing-packages/publishing-docker-images
name: Build and publish JupyterHub image to GHCR

# Run action manually or when called by another action
on: # yamllint disable-line rule:truthy
  workflow_dispatch: {}

  workflow_call:
    inputs:
      ref_name:
        description: "Ref name of github branch"
        required: true
        type: string

  push:
    branches: ['main', 'test']
    tags:
      - "v*.*.*"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: {{ github.GITHUB_REPOSITORY_OWNER }}/opensciencelab-jupyterhub

jobs:
  setup:
    uses: ASFOpenSARlab/osl-utils/.github/workflows/reusable-setup-env.yaml@v1.1.2
    with:
      tagname: ${{ inputs.ref_name || github.ref_name }}

  build-and-push-image:
    runs-on: ubuntu-latest
    needs: setup

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the GitHub Container registry
        uses: docker/login-action@v3.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha
            type=semver,pattern={{raw}}
            type=raw,value=${{ needs.setup.outputs.deploy_prefix }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v7.0.0
        with:
          context: jupyterhub-image
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1.3.2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
